### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by lisammm** [CrossmodalGroup/NAAF#1]
I am interested in this work, could you please release the code?

**Comment by CrossmodalGroup** [comment]
Thanks for your attention, we will update the code during the conference.

**Comment by QinYang79** [comment]
It seems that the ‘final_word_emb’ (1024) of glove does not correspond to the dimension of .pkl (300). 
I get an error:
RuntimeError: input.size(-1) must be equal to input_size. Expected 1024, got 300
