### ISSUE TITLE
configured environment

### ISSUE THREAD

**Issue by getGreat101** [CrossmodalGroup/NAAF#14]
I want to ask how the environment of your code is configured, I tried to use conda env create -f environment3090.yaml in the cloud server to create a new virtual environment to import the configuration, but every time it fails, I want to ask you, what is the correct configuration method, look forward to your reply, thank you

**Comment by CrossmodalGroup** [comment]
Sorry, I don't know why, since everyone has distinct environments. Maybe the version of CUDA?

**Comment by getGreat101** [comment]
Thank you for your reply. I will try again
