### ISSUE TITLE
Glove's dimension error

### ISSUE THREAD

**Issue by QinYang79** [CrossmodalGroup/NAAF#2]
It seems that the ‘final_word_emb’ (1024) of glove does not correspond to the dimension of .pkl (300).
I get an error:
RuntimeError: input.size(-1) must be equal to input_size. Expected 1024, got 300

**Comment by CrossmodalGroup** [comment]
Hi, I suggest you double-check that the loaded vocabulary is correct. I checked that the uploaded code is working fine.

**Comment by QinYang79** [comment]
> double

Thanks, I also rechecked your NAAF's code and it is correct. The reason for the error is that I confused the parameters when migrating “glove”. Thanks again for your reply!

**Comment by QinYang79** [comment]
Could you provide the results of the NAAF (BiGUR w/o glove) on the MS-COCO 5K test? Thanks!
