### ISSUE TITLE
Cannot reproduce the results in the paper

### ISSUE THREAD

**Issue by gzwo-O** [CrossmodalGroup/NAAF#3]
Thanks for your excellent work. I am interested in your work. But I run the result on fl30k datasets according to your hyperparameters in readme.md and my result is very low.  Here are my reimplementation of your model on fl30k dataset.
rsum: 502.6
Average i2t Recall: 89.5
Image to text: 76.8 94.1 97.7 1.0 2.5
Average t2i Recall: 78.0
Text to image: 60.3 84.0 89.7 1.0 7.6
I think I may have missed or didn't understand some details of your model, can you help me? Thank you very much.

**Comment by CrossmodalGroup** [comment]
Hi, all the details have been explained. It is recommended that you debug whether there are other problems such as loading data during operation. My further findings in experiments: 1) Appropriately increase alpha, there may be better performance, for example, alpha is set to 2.5; 2) Increase the batch size during training; 3) Further increase the training epoch, such as 25 epochs.  Finally, it is recommended that you run the code several times, there may be randomness.

**Comment by gzwo-O** [comment]
Hello, thanks for your reply, I improved my results by setting the alpha value to 1, and also setting the batch size to 256. In addition, I also noticed that the result of f30k reported in the paper is the result of model ensemble, so I also ensemble the two trained models, except that the R@1 of i2t is 0.9 lower (this may be a random factor), other indicators are the same as the result reported in th paper , thanks again for sharing your code.

**Comment by gzwo-O** [comment]
> 

Hello, thanks for your reply, I improved my results by setting the alpha value to 1, and also setting the batch size to 256. In addition, I also noticed that the result of f30k reported in the paper is the result of model ensemble, so I also ensemble the two trained models, except that the R@1 of i2t is 0.9 lower (this may be a random factor), other indicators are the same as the result reported in th paper , thanks again for sharing your code.
