### ISSUE TITLE
What do sparse and dense models refer to?

### ISSUE THREAD

**Issue by gzwo-O** [CrossmodalGroup/NAAF#4]
Thanks for sharing your excellent work. In readme.md, for how to run test_stack.py, the instructions point out that the path of sparse model and dense model need to be provided, but I don't know what these two models refer to. When I run it locally, I just run the train code twice to get two models, am I doing it right, looking forward to your reply.

**Comment by CrossmodalGroup** [comment]
Sorry. Please ignore ‘sparse’ and ‘dense’, it may be that I didn't pay attention when I copied GSMN,  where ‘sparse’ and ‘dense’ are the content in GSMN. For the ensemble model, as described in our paper, we report the ensemble results by averaging two models’ similarity, i.e., whether using the intra-modal relationship.

**Comment by gzwo-O** [comment]
Thanks for your reply.
