### ISSUE TITLE
Regarding dimension of GloVe embedding

### ISSUE THREAD

**Issue by kdwonn** [CrossmodalGroup/NAAF#5]
Hello! First of all, thank you for sharing the code of your great work.

While reading your paper, I noticed that your model used the 1024 dimensional GloVe embedding.

However, I can only found the 300 dimensional GloVe embedding in its official website (https://nlp.stanford.edu/projects/glove/).

How did you obtain the 1024-dimensional GloVe?

**Comment by CrossmodalGroup** [comment]
Hi, we refer to https://github.com/jwehrmann/retrieval.pytorch.

**Comment by kdwonn** [comment]
Thank you for the answer! However, I have one more unresolved question. It seems provided code is not actually concatenating GloVe embedding and randomly initialized embedding (line 548 of the model.py). Is it a mistake or intended?

**Comment by CrossmodalGroup** [comment]
Hi, we didn't do it the way the reference was used (as you mentioned concatenating or randomly initialising).
