### ISSUE TITLE
About the precision

### ISSUE THREAD

**Issue by ahustr** [CrossmodalGroup/NAAF#7]
Hello, I'm very interested in your work. However, why I can't get this precision by running the code directly.
This is my best result for Flicker30k:  
rsum: 497.8
Average i2t Recall: 88.7
Image to text: 75.5 93.0 97.7 1.0 2.6
Average t2i Recall: 77.2
Text to image: 58.6 83.5 89.6 1.0 7.5

**Comment by ahustr** [comment]
For Flicker30k

**Comment by Paranioar** [comment]
This is my result for F30K with Glove embedding:
rsum: 499.4
Average i2t Recall: 88.8
Image to text: 75.1 94.0 97.2 1.0 2.3
Average t2i Recall: 77.7
Text to image: 58.9 84.1 90.1 1.0 7.4

and result for F30K with random initialization:
rsum: 484.9
Average i2t Recall: 86.9
Image to text: 71.5 92.9 96.3 1.0 3.0
Average t2i Recall: 74.7
Text to image: 55.6 80.8 87.7 1.0 9.7

Is there anything in particular I should pay attention to?

**Comment by ahustr** [comment]
> 



> This is my result for F30K with Glove embedding: rsum: 499.4 Average i2t Recall: 88.8 Image to text: 75.1 94.0 97.2 1.0 2.3 Average t2i Recall: 77.7 Text to image: 58.9 84.1 90.1 1.0 7.4
> 
> and result for F30K with random initialization: rsum: 484.9 Average i2t Recall: 86.9 Image to text: 71.5 92.9 96.3 1.0 3.0 Average t2i Recall: 74.7 Text to image: 55.6 80.8 87.7 1.0 9.7
> 
> Is there anything in particular I should pay attention to?

**Comment by cavacleves** [comment]
Hello，I am interested in your work. and I have browsed your code, I found some questions
1)
![image](https://user-images.githubusercontent.com/93373862/190976567-33d9cf8e-0cd5-405d-b1f9-bbe9b04ea680.png)
This is the calculation method of cross modal similarity in the article, but in your code you did not divide the result by the corresponding norm
![image](https://user-images.githubusercontent.com/93373862/190977021-d0437ff3-1ad8-4829-b1f4-ea941a2a7e7f.png)
2) You mentioned the intra-semantic relationship of word fragments within the text in your paper, but why is there no such process in the training process, but only in the test in your code.
I think I may have missed or did not understand some details of your model ,can you help me ? Thank you very much.

**Comment by rshouX** [comment]
Actually I increase the alpha, however, I still cannot reach the result proposed by author in paper.
