### ISSUE TITLE
About the initial penalty paramater a 

### ISSUE THREAD

**Issue by TitleZ99** [CrossmodalGroup/NAAF#8]
Thans a lot for this wonderful work , i can't find the specific derivation in the supplementary material you mentioned in your paper. i want to figure out why initial a in this way. so can you share your supplementary material with me? So that i can learn it more.

**Comment by kkzhang95** [comment]
Hi, you can download the supplementary material at: https://openaccess.thecvf.com/content/CVPR2022/html/Zhang_Negative-Aware_Attention_Framework_for_Image-Text_Matching_CVPR_2022_paper.html

The idea about alpha: we experimentally found that a relatively large alpha in training benefits the performance, while this large alpha is harmful to the testing stage that misadjusts many relevant word-region fragments. Thus, we design to initial alpha with a large value and then re-assign an appropriate value (ensuring the learned boundary at the lower bound of relevant distribution).  This can not only ensure effective training but also reduce interference during testing.
